domain: js-date.wex
git:
  main_deployment_remote_name: github
  publication_strategy: main_push
global:
  name: js-date
  type: javascript-package
  version: 1.0.5
wex:
  migration: 7
  version: 6.0.136
